import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/navbar";
import { Open_Sans } from "next/font/google";
import "@mantine/dates/styles.css";
import "@mantine/core/styles.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  //👇 Add variable to our object
  variable: "--font-opensans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <body className="bg-[#F5F5F5]">
        {" "}
        <main className="pt-16">
          <div className={openSans.variable}>{children}</div>
        </main>
      </body>
      {/* Add padding top to main */}
    </html>
  );
}
