import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <Sidebar />
      <body className="bg-[#F5F5F5]"> <main className="pt-16">{children}</main></body>
      {/* Add padding top to main */}
    </html>
  );
}
